// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.36.2
// source: module.proto

package modulev1

import (
	v1 "github.com/agent-wow/agent-wow/pkg/modules/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Milliseconds from the session's monotonic origin, modulo 2^32.
	ClientTimeMs    uint32 `protobuf:"varint,1,opt,name=client_time_ms,json=clientTimeMs,proto3" json:"client_time_ms,omitempty"`
	PacketsReceived uint32 `protobuf:"varint,2,opt,name=packets_received,json=packetsReceived,proto3" json:"packets_received,omitempty"`
	// Unix seconds from the latest reply; absent until a reply arrives.
	ServerTimeUnix *uint32 `protobuf:"varint,3,opt,name=server_time_unix,json=serverTimeUnix,proto3,oneof" json:"server_time_unix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_module_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_module_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_module_proto_rawDescGZIP(), []int{0}
}

func (x *StatusResponse) GetClientTimeMs() uint32 {
	if x != nil {
		return x.ClientTimeMs
	}
	return 0
}

func (x *StatusResponse) GetPacketsReceived() uint32 {
	if x != nil {
		return x.PacketsReceived
	}
	return 0
}

func (x *StatusResponse) GetServerTimeUnix() uint32 {
	if x != nil && x.ServerTimeUnix != nil {
		return *x.ServerTimeUnix
	}
	return 0
}

var File_module_proto protoreflect.FileDescriptor

const file_module_proto_rawDesc = "" +
	"\n" +
	"\fmodule.proto\x12\x11example.module.v1\x1a\x1bapi/module/v1/session.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xa5\x01\n" +
	"\x0eStatusResponse\x12$\n" +
	"\x0eclient_time_ms\x18\x01 \x01(\rR\fclientTimeMs\x12)\n" +
	"\x10packets_received\x18\x02 \x01(\rR\x0fpacketsReceived\x12-\n" +
	"\x10server_time_unix\x18\x03 \x01(\rH\x00R\x0eserverTimeUnix\x88\x01\x01B\x13\n" +
	"\x11_server_time_unix2\x8f\x02\n" +
	"\x06Module\x12C\n" +
	"\x06Status\x12\x16.google.protobuf.Empty\x1a!.example.module.v1.StatusResponse\x12;\n" +
	"\tQueryTime\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12C\n" +
	"\bOnPacket\x12\x1f.agentwow.module.v1.WorldPacket\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\fBeforeLogout\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyB:Z8github.com/agent-wow/go-module-template/src/api;modulev1b\x06proto3"

var (
	file_module_proto_rawDescOnce sync.Once
	file_module_proto_rawDescData []byte
)

func file_module_proto_rawDescGZIP() []byte {
	file_module_proto_rawDescOnce.Do(func() {
		file_module_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_module_proto_rawDesc), len(file_module_proto_rawDesc)))
	})
	return file_module_proto_rawDescData
}

var file_module_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_module_proto_goTypes = []any{
	(*StatusResponse)(nil), // 0: example.module.v1.StatusResponse
	(*emptypb.Empty)(nil),  // 1: google.protobuf.Empty
	(*v1.WorldPacket)(nil), // 2: agentwow.module.v1.WorldPacket
}
var file_module_proto_depIdxs = []int32{
	1, // 0: example.module.v1.Module.Status:input_type -> google.protobuf.Empty
	1, // 1: example.module.v1.Module.QueryTime:input_type -> google.protobuf.Empty
	2, // 2: example.module.v1.Module.OnPacket:input_type -> agentwow.module.v1.WorldPacket
	1, // 3: example.module.v1.Module.BeforeLogout:input_type -> google.protobuf.Empty
	0, // 4: example.module.v1.Module.Status:output_type -> example.module.v1.StatusResponse
	1, // 5: example.module.v1.Module.QueryTime:output_type -> google.protobuf.Empty
	1, // 6: example.module.v1.Module.OnPacket:output_type -> google.protobuf.Empty
	1, // 7: example.module.v1.Module.BeforeLogout:output_type -> google.protobuf.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_module_proto_init() }
func file_module_proto_init() {
	if File_module_proto != nil {
		return
	}
	file_module_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_module_proto_rawDesc), len(file_module_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_module_proto_goTypes,
		DependencyIndexes: file_module_proto_depIdxs,
		MessageInfos:      file_module_proto_msgTypes,
	}.Build()
	File_module_proto = out.File
	file_module_proto_goTypes = nil
	file_module_proto_depIdxs = nil
}
